#TODO: should be node:10.16.0
FROM node:10
EXPOSE 4200

WORKDIR /usr/src/app

COPY ["package.json", "package-lock.json*","./"]

# install app dependencies...
RUN npm install
RUN npm install -g @angular/cli@7
